global:
  imagePullPolicy: Always
  mongodb:
    port: 27017
    user: reports
    password: reportspassword
    db: sausage-store

  vault:
    host: 111.88.247.60
    name: vault
    port: 8201
  ###  vaultToken: someToken


frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-ivan.2sem.students-projects.ru 
    path: /
    pathType: Prefix
    secretName: 2sem-students-projects-wildcard-secret
  containerPort: 80
  image: vanchello/sausage-frontend:latest
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "1"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image: vanchello/sausage-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "256Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "1"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
  vpa:
    updatePolicy:
      updateMode: Off
    resourcePolicy:
      containerPolicy:
        - containerName: "*"
          minAllowed:
            cpu: 100m
            memory: 128Mi
          maxAllowed:
            cpu: 500m
            memory: 512Mi
          controlledResources:
            - cpu
            - memory

backend-report:
  image: vanchello/backend-report:latest
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  recources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
  containerPort: 8080
  hpa:
    minReplicas: 1
    maxReplicas: 3
    metrics:
      - type: Resource
        recource:
          name: cpu
          target:
            averageUtilization: 60
            type: Utilization
  service:
    port: 8080


infra:
  postgresql:
    image: postgresql:18-trixie
    ports:
      port: 5432
      containerPort: 5432
    volume:
      mountPath: /var/lib/postgresql
    data:
      POSTGRES_PASSWORD: storepassword
      POSTGRES_USER: store
      POSTGRES_DB: sausage-store

  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
