apiVersion: batch/v1
kind: Job
metadata:
  name: db-user-create
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-user-and-db
          image: mongo:7.0
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD }}
          command:
            - sh
            - -c
            - |
              mongosh --host mongodb \
                -u "$MONGO_INITDB_ROOT_USERNAME" \
                -p "$MONGO_INITDB_ROOT_PASSWORD" \
                --authenticationDatabase admin \
                --eval "
                  use {{ .Values.global.mongodb.db }};
                  if (db.getUser('{{ .Values.global.mongodb.user }}') === null) {
                    db.createUser({
                      user: '{{ .Values.global.mongodb.user }}',
                      pwd: '{{ .Values.global.mongodb.password }}',
                      roles: [{ role: 'readWrite', db: '{{ .Values.global.mongodb.db }}' }]
                    });
                    print('User created');
                  } else {
                    print('User already exists');
                  }
                "