apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db: mongodb://{{ .Values.global.mongodb.user }}:{{ .Values.global.mongodb.password }}@mongodb:{{ .Values.global.mongodb.port }}/{{ .Values.global.mongodb.db }}